# Data configuration
data:
  raw_data_path: "data/raw/customer_data.csv"
  processed_data_path: "data/processed/customer_data_processed.csv"
  test_size: 0.2
  random_state: 42
  target_column: "churn"
  id_column: "customer_id"

# Feature engineering
features:
  categorical_features:
    - "gender"
    - "contract_type"
    - "payment_method"
  numerical_features:
    - "tenure"
    - "monthly_charges"
    - "total_charges"
  datetime_features: []
  drop_features: []
  categorical_imputation_strategy: "most_frequent"
  numerical_imputation_strategy: "median"

# Model training
model:
  algorithm: "random_forest"  # Options: logistic_regression, random_forest, xgboost, lightgbm
  hyperparameters:
    random_forest:
      n_estimators: 100
      max_depth: 10
      min_samples_split: 2
      min_samples_leaf: 1
      random_state: 42
    logistic_regression:
      C: 1.0
      penalty: "l2"
      solver: "liblinear"
      random_state: 42
    xgboost:
      n_estimators: 100
      max_depth: 6
      learning_rate: 0.1
      subsample: 0.8
      colsample_bytree: 0.8
      random_state: 42
    lightgbm:
      n_estimators: 100
      max_depth: 6
      learning_rate: 0.1
      num_leaves: 31
      random_state: 42

# Model evaluation
evaluation:
  metrics:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1"
    - "roc_auc"
  threshold: 0.5
  production_min_accuracy: 0.75

# Pipeline
pipeline:
  run_data_validation: true
  run_data_preparation: true
  run_feature_engineering: true
  run_training: true
  run_evaluation: true
  run_deployment: true
  
# Artifacts
artifacts:
  base_path: "artifacts"
  model_registry_path: "model_registry"
  metadata_path: "metadata"
  
# Monitoring
monitoring:
  data_drift_threshold: 0.1
  performance_threshold: 0.05
  monitoring_frequency: "daily"  # Options: hourly, daily, weekly
  alerts_enabled: true
  
# Database
database:
  type: "sqlite"  # Options: sqlite, postgres
  sqlite:
    path: "data/mlops.db"
  postgres:
    host: "localhost"
    port: 5432
    user: "mlops"
    password: "mlops"
    database: "mlops"
    
# Prefect
prefect:
  flow_name: "customer_churn_pipeline"
  log_level: "INFO"
  
# Deployment
deployment:
  api_port: 8000
  api_workers: 2
  timeout: 60
  batch_size: 1000
