model_params:
  n_estimators: 100
  max_depth: 10
  min_samples_split: 2
  min_samples_leaf: 1
  random_state: 42

data_config:
  target_column: "target"
  features:
    - "feature1"
    - "feature2"
    - "feature3"

training_config:
  test_size: 0.2
  random_state: 42
