data_ingestion:
  database:
    host: "localhost"
    port: 5432
    dbname: "mydatabase"
    user: "myuser"
    password: "mypassword"
  cloud_storage:
    bucket_name: "my-bucket"
    aws_access_key_id: "my-access-key"
    aws_secret_access_key: "my-secret-key"

model_training:
  mlflow_tracking_uri: "http://localhost:5000"
  experiment_name: "my_experiment"

monitoring:
  prometheus_port: 9090
  grafana_dashboard_url: "http://localhost:3000"


data_ingestion:
  type: "default"  # Can be "default", "s3", "database", etc.
  params:
    database_url: "postgresql://user:password@localhost:5432/mydb"

model_training:
  type: "mlflow"
  params:
    tracking_uri: "http://localhost:5000"
    experiment_name: "my_experiment"

monitoring:
  type: "prometheus"
  params:
    port: 9090