execution:
  option_run: local  # Options: local, cloud
  option_scale: local  # Options: local, docker

data:
  target_column: target

data_split:
  train_size: 0.8

features:
  categorical_features: []
  numerical_features: []

model:
  type: random_forest
  n_estimators: 100
  max_depth: None

monitoring:
  prometheus_port: 9090
  dashboard_path: monitoring

deployment:
  flask_port: 5000

retraining:
  metric_threshold:
    accuracy: 0.8
    f1: 0.7