data:
  test_size: 0.2
  random_state: 42
model:
  n_estimators: 100
  max_depth: 5
mlflow:
  tracking_uri: "http://localhost:5000"
deployment:
  host: "0.0.0.0"
  port: 5001
monitoring:
  report_path: "reports/data_drift.html"