data:
  path: "data/data.csv"
  target_column: "target"
  train_size: 0.8

features:
  numerical_features: ["feature1", "feature2"]
  categorical_features: ["category1", "category2"]

model:
  type: "random_forest"
  n_estimators: 100
  max_depth: 5
  version: "v1.0.0"

deployment:
  flask_port: 5000
  kubernetes:
    enabled: true
    namespace: "mlops-prod"
    ingress_name: "model-ingress"

monitoring:
  prometheus_port: 9090
  dashboard_path: "monitoring/dashboard.html"
  metrics:
    - accuracy
    - precision
    - recall
    - f1

retraining:
  metric_threshold:
    accuracy: 0.85
    f1: 0.8

feature_store:
  repo_path: "feature_repo/"
  feature_views:
    - customer_features
    - transaction_features

dvc:
  remote_url: "s3://your-bucket/dvc-storage"
  data_path: "data/data.csv"

grafana:
  dashboard_path: "grafana/dashboards/"