base:
  test_size: 0.2
  random_state: 42

folder_path:
  artifacts: "artifacts"
  raw_data: "raw_data"
  processed_data: "processed_data"
  features: "features"
  models: "models"
  evaluation: "evaluation"

processing:
  numeric_columns: ["col1", "col2"]
  categorical_columns: ["cat1", "cat2"]
  handle_outliers: true
  outlier_threshold: 3

feature_engineering:
  one_hot_encode: true
  create_interactions: true
  create_polynomial: true

model:
  feature_columns: []  # If empty, will use all except target
  target_column: "target"
  random_forest:
    n_estimators: 100
    max_depth: 10
  gradient_boosting:
    n_estimators: 100
    learning_rate: 0.1
  logistic_regression:
    C: 1.0
    max_iter: 1000



python ml_pipeline.py --data your_data.csv --config your_config.yml